apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-booking
  namespace: staging-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: room-booking
  template:
    metadata:
      labels:
        app: room-booking
    spec:
      containers:
        - name: room-booking
          image: rhan33/room-booking:staging-16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80

          env:
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: room-booking-secret
                  key: APP_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5

